Valkiria-Project/SISEM-Android

- app/src/main/java/com/skgtecnologia/sisem/ui/theme/Theme.kt
> [Fix]: onSurface text color to white

- app/src/main/java/com/skgtecnologia/sisem/data/authcards/AuthCardsRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/AuthCardsCacheDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/dao/ConfigDao.kt
- app/src/main/java/com/skgtecnologia/sisem/data/authcards/cache/model/ConfigEntity.kt
- app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsApi.kt
- app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/AuthCardsRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/authcards/remote/model/ConfigResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
- app/src/main/java/com/skgtecnologia/sisem/di/CoreDatabaseModule.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/authcards/AuthCardsRepository.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/ConfigModel.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/authcards/usecases/Config.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/authcards/usecases/GetConfig.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsViewModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardComponent.kt
> [Feature]: Add config

- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/props/MarginsResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/screen/Params.kt
> [Fix]: Make json properties snake case

- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/screen/Params.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
- uicomponents/src/main/res/drawable/ic_check.xml
> [Fix]: Add menu options and turn_id param

- app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/model/AccessTokenEntity.kt
- app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/AccessTokenResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/auth/model/AccessTokenModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
> [Fix]: optional turn param

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/domain/login/model/LoginIdentifier.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/LoginNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
- Add navigation logic for LoginScreen.
- Launch the App.
- Check that the business rules for navigation when Loggin in are meet
> [Feature]: Add navigation logic for LoginScreen

- app/src/main/java/com/skgtecnologia/sisem/ui/SisemComposeApp.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberItemModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
> [Fix]: Admin menu and code ambulance cancel job

- app/src/main/java/com/skgtecnologia/sisem/domain/model/bricks/ChipSectionModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/FindingsContent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/crewmembercard/CrewMemberCardComponent.kt
- uicomponents/src/main/res/drawable/ic_finding.xml
> [Fix]: Chip section action show bottom sheet

- gradle/libs.versions.toml
> [Chore]: Bump AGP to 8.1.1

- app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/di/auth/AuthNetworkModule.kt
- Update BASE_URL to `http://34.139.125.3:80/sisem-api/` and `http://34.139.125.3:80/sisem-api/v1/`
- Run the app.
> [Feature]: Update BASE_URL

- app/src/main/java/com/skgtecnologia/sisem/domain/model/body/CrewMemberCardModel.kt
Co-authored-by: Juan Vilada <jvillad1@gmail.com>## Summary
> [Fix]: Humanized name in card member component

- app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/model/AccessTokenEntity.kt
- app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/model/AccessTokenResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/PreOperationalRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/di/operation/OperationRole.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/auth/model/AccessTokenModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberItem.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberMenuItemModel.kt
> [Fix]: add user document to menu

- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DigitsTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/inventorycheck/InventoryCheckComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
- Add logic for Pre Operational inputs validation.
> [Fix]: Add logic for Pre Operational inputs validation

- app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/model/OperationEntity.kt
- app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/model/OperationResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/OperationModel.kt
> [Fix]: Optional vehicle code

- app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
> [Fix]: Logout of other users if the administrator authenticates

- app/build.gradle.kts
> [Chore]: Bump version to 0.1.1

- app/build.gradle.kts
- app/src/main/AndroidManifest.xml
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AuditInterceptor.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/body/TextFieldResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/di/ApplicationModule.kt
- app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/di/CoreNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/di/auth/AuthNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/di/qualifiers/Qualifiers.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/model/body/TextFieldModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/LocationExtensions.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/map/MapUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/map/MapViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/DrawerContent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerMenuItemModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItem.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItemsComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
- gradle/libs.versions.toml
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/textfield/TextFieldUiModel.kt
> [Bugfix]: Add location logic

- app/src/main/AndroidManifest.xml
- app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/AuthCacheDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
- app/src/main/java/com/skgtecnologia/sisem/data/operation/cache/OperationCacheDataSource.kt
> [Bugfix]: Data storage related fixes

- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsContent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsViewModel.kt
> [Fix]: Bottom sheet problem solved

- app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/RetrofitExtensions.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
- app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
- Add AccessTokenAuthenticator for AccessToken refresh.
> [Feature]: Add AccessTokenAuthenticator

- uicomponents/build.gradle.kts
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
- Add DatePickerTextFieldView.
> [Feature]: Add DatePickerTextFieldView

- app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/RetrofitExtensions.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
- app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
- uicomponents/build.gradle.kts
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
> [Chore]: Version 0.3.0 testing

- app/src/main/java/com/skgtecnologia/sisem/data/auth/AuthRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/extensions/RetrofitExtensions.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
- app/src/main/java/com/skgtecnologia/sisem/di/BearerNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/auth/AuthRepository.kt
- uicomponents/build.gradle.kts
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
> [Chore]: Merge back (#94)

- app/src/main/java/com/skgtecnologia/sisem/domain/model/body/SliderModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/slider/SliderComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/model/ui/slider/SliderUiModel.kt
- uicomponents/src/main/res/drawable/ic_slider_shape.xml
> [Feat]: Slider component

- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
> [Fix]: adjust info card component

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/domain/login/model/LegalContentModel.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/login/model/LoginLink.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/report/ReportContent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyBackComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/HumanBodyFrontComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginHeaderSection.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/legal/LegalContent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/footer/MenuFooterComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/CrewMemberItem.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/MenuHeaderComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/MenuItem.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/HeaderSection.kt
- uicomponents/build.gradle.kts
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/banner/BannerView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/detailedinfolist/DetailedInfoListComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/slider/SliderComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/PasswordTextFieldComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
> [BugFix]: SMA-177 & SMA-202

- app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportViewModel.kt
- app/src/main/res/values/strings.xml
- Fix SMA-223 -> CP HU 00272 CA 01.
> [BugFix]: SMA-223 -> CP HU 00272 CA 01

- app/src/main/java/com/skgtecnologia/sisem/data/preoperational/remote/model/NoveltyBody.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AuditInterceptor.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/textfield/TextFieldResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/preoperational/model/Novelty.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/report/model/ImageModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/commons/extensions/BitmapExtensions.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/media/ImagesConfirmationScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/PreOpNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/model/ReportNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/AddFindingScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/AddReportScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
- gradle/libs.versions.toml
- settings.gradle.kts
> [Bugfix]: SMA-183

- uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
> [Fix]: Add ellipse to pill

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/AuthCardsScreen.kt
> [Bugfix]: SMA-289

- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
> [Fix]: keep textfield user value saveable in viewmodel

- app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/MedicalHistoryRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/PreOperationalViewModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/button/ImageButtonSectionComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/InputUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
> [Bugfix]: SMA-288 Part 2

- uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
> [Fix]: End dp logic to pill in info card component

- app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/model/MedicalHistoryKeys.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/vitalsings/VitalSignsViewModel.kt
> [Fix]: SMA-295 part 1, SMA-296 point 2-3, SMA-298

- app/src/main/java/com/skgtecnologia/sisem/data/forgotpassword/ForgotPasswordRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/forgotpassword/remote/ForgotPasswordApi.kt
- app/src/main/java/com/skgtecnologia/sisem/data/forgotpassword/remote/ForgotPasswordRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/di/forgotpassword/ForgotPasswordNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/di/forgotpassword/ForgotPasswordRepositoryModule.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/ForgotPasswordRepository.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/model/ForgotPasswordIdentifier.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/usecases/GetForgotPasswordScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/forgotpassword/usecases/SendEmail.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/forgotpassword/ForgotPasswordViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
- uicomponents/src/main/res/drawable/ic_email.xml
> [Feat]: Forgot password screen and logic

- app/src/main/java/com/skgtecnologia/sisem/data/stretcherretention/StretcherRetentionRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/stretcherretention/remote/StretcherRetentionApi.kt
- app/src/main/java/com/skgtecnologia/sisem/data/stretcherretention/remote/StretcherRetentionRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/stretcherretention/remote/model/StretcherRetentionBody.kt
- app/src/main/java/com/skgtecnologia/sisem/di/stretcherretention/StretcherRetentionNetworkModule.kt
- app/src/main/java/com/skgtecnologia/sisem/di/stretcherretention/StretcherRetentionRepositoryModule.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/stretcherretention/StretcherRetentionRepository.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/stretcherretention/usecases/GetStretcherRetentionScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/stretcherretention/usecases/SaveStretcherRetention.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerMenuItemModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationProps.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationSolver.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionViewModel.kt
- app/src/main/res/values/strings.xml
- uicomponents/src/main/res/drawable/ic_stretcher.xml
> [Feat]: Stretcher retention screen

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/vitalsings/VitalSignsViewModel.kt
> [Fix]: Calculate TAM

- app/src/main/java/com/skgtecnologia/sisem/domain/model/banner/BusinessBannerModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
> [Fix]: SMA-308 - wounds content

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/splash/SplashViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/commons/MainDispatcherRule.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/splash/SplashViewModelTest.kt
- gradle/libs.versions.toml
> [Test]: Initital test configuration

- app/build.gradle.kts
> [Chore]: Bump version to 0.7.1

- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/login/LoginViewModelTest.kt
> [Test]: Login ViewModel

- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/authcards/create/AuthCardsViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/login/LoginViewModelTest.kt
> [Test]: Auth cards view model

- app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordViewModelTest.kt
> [Test]: Change password viewModel

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/vitalsings/VitalSignsViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/inventory/InventoryViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/vitalsings/VitalSignsViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/menu/MenuViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/report/ReportViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/stretcherretention/StretcherRetentionViewModelTest.kt
> [Test]: Menu - Report view models 

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedsSelectorComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/chip/FilterChipView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/extensions/ChipExtensions.kt
> [Fix]: SMA-315 and SMA-316 dissenting ordering between date and name in meds selector

- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/textfield/TextFieldResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/preoperational/create/PreOperationalViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FilledTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/InputUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldUiModel.kt
> [Fix]: Add validations for text fields in medical history

- app/src/main/java/com/skgtecnologia/sisem/ui/menu/header/MenuHeaderComponent.kt
- app/src/preProd/google-services.json
- app/src/preProd/res/values/strings.xml
- uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/IncidentContent.kt
- uicomponents/src/main/res/values/strings.xml
> [Feature]: Finish Incident Opening

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewScreen.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/timeline/TimelineComponent.kt
> [Fix]: Timeline component

- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipSelectionResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/segmentedswitch/SegmentedSwitchResponse.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/segmentedswitch/SegmentedSwitchUiModel.kt
> [Fix]: change String to List in of String in view visibility

- app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/MedicalHistoryRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/medicalhistory/remote/MedicalHistoryRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/MedicalHistoryRepository.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/GetMedicineScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/domain/medicalhistory/usecases/GetMedicineScreenTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModelTest.kt
> [Fix]: Add serial to medicine screen

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/AuthCacheDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/auth/cache/dao/AccessTokenDao.kt
- app/src/main/java/com/skgtecnologia/sisem/data/operation/OperationRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/OperationApi.kt
- app/src/main/java/com/skgtecnologia/sisem/data/operation/remote/OperationRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AuditInterceptor.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/operation/OperationRepository.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/LogoutTurn.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/menu/MenuViewModelTest.kt
- Add logout turn funtionality.
> [Feature]: Add logout turn funtionality

- .idea/deploymentTargetSelector.xml
- app/src/main/java/com/skgtecnologia/sisem/data/operation/OperationRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/model/label/BusinessLabelModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerMenuItemModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/addfinding/AddFindingScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportRoleScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportRoleViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/report/addreport/AddReportViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
> [Bugfix]: Android version 0.15

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/create/report/FindingsContent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/DatePickerTextFieldView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/FixedDateTextFieldView.kt
> chore: bump version to 0.18.0

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionItemUiModel.kt
- Fix SMA-311, SMA-313, SMA-326, SMA-330, SMA-331, SMA-332, SMA-334, SMA-335.
> [Fix]: Validate chip option, chip selection, dropdown and fields in aph

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/signaturepad/SignaturePadScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewViewModel.kt
- gradle/libs.versions.toml
- uicomponents/build.gradle.kts
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/signature/ComposeSignature.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/signature/PathState.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/signature/SignaturePadViewModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/SignatureComponent.kt
> [Feature]: Version 1.0.0

- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipOptionsResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipOptionsUiModel.kt
https://github.com/Valkiria-Project/SISEM-Android/assets/19801948/debcbb95-9e24-4fbe-b708-53f8192eb2e2
> [Fix]: SMA-418

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/MainActivity.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- gradle/libs.versions.toml
- gradle/wrapper/gradle-wrapper.properties
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/notification/NotificationView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/signature/ComposeSignature.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/SignatureComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/slider/SliderComponent.kt
> [Chore]: Android version to 1.2.0

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
- uicomponents/src/main/res/values/strings.xml
SMA-390: time component is modified to show time picker and be able to select a time
https://github.com/Valkiria-Project/SISEM-Android/assets/19801948/2cb80c54-bd13-403e-9e55-716eb18e53c7
> [Fix]: SMA-390

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/report/media/ImagesConfirmationScreen.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/report/ReportViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/label/LabelUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/extensions/FileExtensions.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/utlis/TimeUtils.kt
> [Chore]: Release 1.4.0

- app/build.gradle.kts
> [Fix]: Base url pre-prod

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/domain/authcards/model/VehicleConfigModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuDrawer.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/MenuViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/menu/MenuViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapboxMapView.kt
> [Chore] Android release 1.5.3

- .idea/misc.xml
- .idea/other.xml
- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/data/cache/SisemDatabase.kt
- app/src/main/java/com/skgtecnologia/sisem/data/incident/cache/model/IncidentEntity.kt
- app/src/main/java/com/skgtecnologia/sisem/data/notification/NotificationRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/auth/model/AccessTokenModel.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/auth/usecases/Login.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/operation/model/PreoperationalStatus.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/operation/usecases/GetStartupState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/authcards/view/AuthCardViewScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/login/LoginViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationCoordinator.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
- app/src/test/java/com/skgtecnologia/sisem/domain/auth/usecases/LoginTest.kt
- app/src/test/java/com/skgtecnologia/sisem/domain/operation/usecases/GetStartupStateTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/button/ImageButtonView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapboxMapView.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/incident/model/IncidentUiModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/media/MediaActionsComponent.kt
> [Chore] Android release 1.6.0

- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/dropdown/DropDownResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownContent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView.kt
[SMA-313](https://skgtecnologia.atlassian.net/browse/SMA-313) - Solved
[SMA-434](https://skgtecnologia.atlassian.net/browse/SMA-434) - Solved
[SMA-331](https://skgtecnologia.atlassian.net/browse/SMA-331):
- The native part for the dropdown button is solved
- Needs to be solved from backend
> [Fix]: SMA-313 and SMA-434 

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/changepassword/ChangePasswordScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/view/MedicalHistoryViewViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/preoperational/view/PreOperationalViewViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/build.gradle.kts
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/FiltersComponent.kt
> [Chore] Android release 1.8.0

- app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
- Fix reportado por QA -  sin ticket
- [SMA-331](https://skgtecnologia.atlassian.net/browse/SMA-331)
> Fix: don't equals dropdown ids

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/theme/Type.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/label/TextStyle.kt
> [Chore] Android release 1.8.2

- uicomponents/src/main/java/com/valkiria/uicomponents/components/card/InfoCardComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/extensions/ModifierExtensions.kt
- [SMA-234](https://skgtecnologia.atlassian.net/browse/SMA-234)
> Fix: SMA-234

- app/src/main/java/com/skgtecnologia/sisem/ui/dropdown/DropDownComponent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
> Fix: SMA-331 and SMA-478

- app/src/main/java/com/skgtecnologia/sisem/ui/inventory/view/InventoryViewViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/textfield/OutlinedTextFieldView2.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent2.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/textfield/TextFieldComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/extensions/TextFieldExtensions.kt
[SMA-440](https://skgtecnologia.atlassian.net/browse/SMA-440)
[SMA-406](https://skgtecnologia.atlassian.net/browse/SMA-406)
> Fix: SMA-440 and SMA-406

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerComponent.kt
> Fix: SMA-390

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/signature/SignatureComponent.kt
> Fix: SMA-485

- .idea/misc.xml
- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenInterceptor.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/RemoteConstants.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/model/components/chip/ChipSelectionResponse.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/humanbody/wounds/WoundsContent.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/sections/BodySection.kt
- app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/action/UiAction.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionComponent.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/chip/ChipSelectionUiModel.kt
> [Chore] Android release 1.8.5

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/medicine/MedicineViewModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/components/timepicker/TimePickerComponent.kt
[SMA-502](https://skgtecnologia.atlassian.net/browse/SMA-502)
[SMA-390](https://skgtecnologia.atlassian.net/browse/SMA-390)
> [Fix]: SMA-502 and SMA-390

- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/commons/TestConstants.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/medicalhistory/MedicalHistoryViewModelTest.kt
[SMA-315](https://skgtecnologia.atlassian.net/browse/SMA-315)
> [Fix]: SMA-315

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/data/location/LocationRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/location/remote/LocationRemoteDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/location/remote/model/LocationBody.kt
- app/src/main/java/com/skgtecnologia/sisem/data/notification/NotificationRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/notification/cache/NotificationCacheDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/notification/cache/dao/NotificationDao.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenAuthenticator.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/AccessTokenInterceptor.kt
- app/src/main/java/com/skgtecnologia/sisem/data/remote/interceptors/RemoteConstants.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/create/MedicalHistoryViewModel.kt
> [Chore] Android release 1.9.2

- app/build.gradle.kts
- app/src/main/java/com/skgtecnologia/sisem/ui/report/ReportViewModel.kt
- app/src/test/java/com/skgtecnologia/sisem/ui/report/ReportViewModelTest.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/extensions/FileExtensions.kt
> [Chore] Android release 1.9.3

- .idea/gradle.xml
- .idea/misc.xml
- app/src/main/java/com/skgtecnologia/sisem/ui/medicalhistory/create/MedicalHistoryViewModel.kt
[SMA-482](https://skgtecnologia.atlassian.net/browse/SMA-482)
> [Fix]: SMA-482

- app/src/main/java/com/skgtecnologia/sisem/data/auth/remote/AuthApi.kt
> [Chore] Android release 1.9.8

- app/src/main/java/com/skgtecnologia/sisem/data/notification/NotificationRepositoryImpl.kt
- app/src/main/java/com/skgtecnologia/sisem/data/notification/cache/NotificationCacheDataSource.kt
- app/src/main/java/com/skgtecnologia/sisem/data/notification/cache/dao/NotificationDao.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/incident/usecases/ObserveActiveIncident.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/notification/repository/NotificationRepository.kt
- app/src/main/java/com/skgtecnologia/sisem/domain/notification/usecases/ObserveNotifications.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/map/MapScreen.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/map/MapUiState.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/map/MapViewModel.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapFragment.kt
- uicomponents/src/main/java/com/valkiria/uicomponents/bricks/map/MapboxMapView.kt
> [feature]: Add last location to map

- .idea/kotlinc.xml
- app/src/main/java/com/skgtecnologia/sisem/ui/deviceauth/DeviceAuthNavigationModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/menu/items/DrawerMenuItemModel.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/NavigationRoutes.kt
- app/src/main/java/com/skgtecnologia/sisem/ui/navigation/SisemNavGraph.kt
- Fix navigation logic for DeviceAuthNavigationModel
> [Fix][SMA-559]: Fix navigation logic for DeviceAuthNavigationModel
